### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by NixFull** [odiseoteam/RbacPlugin#5]
Sylius : 1.9
Symphony: 5.2.4

Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in vendor/odiseoteam/sylius-rbac-plugin/src/DependencyInjection/Configuration.php on line 17 and at least 1 expected

**Comment by bigboss86** [comment]
Resolved! Thanks @NixFull
